### ISSUE TITLE
Remove node_modules

### ISSUE THREAD

**Issue by emmysteven** [AdioleDivine/nigerian-universities#4]
Hi 👋🏻

I wanted to discuss this, before making a pull request
I love what you've done with this project, however, it will be great to see the node_modules removed from the project

I'll suggest that a commit be made that removes node_modules from the project, and I could assist with that, that way I have the opportunity to contribute to your open source project.

Regards!

**Comment by JoelOvien** [comment]
The node_modules would be removed, Thanks a lot
